version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
  ui:
    build:
      context: ./ui/whiteboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"