server:
  port:8083

spring:
  application:
    name: user-service
  datasource:
    username: 'root'
    url: jdbc:mysql://localhost:5001/user
    password: 'pass123'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
  security:
    user:
      name: 'user'
      password: 'pass'
